version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

sphinx:
  configuration: docs/conf.py

conda:
  environment: docs/docs_environment.yml

python:
  version: 3.8
  install:
    - method: pip
      path: .
