version: 2

sphinx:
  configuration: docs/conf.py

formats:
  - pdf

submodules:
  include: all

conda:
  environment: docs/docs_environment.yml

python:
  version: 3.7
  install:
    - method: pip
      path: .